import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  dropdownMenuContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 10,
    minWidth: 180,
    maxWidth: 220,
    zIndex: 2000,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  dropdownMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f1',
  },
  dropdownMenuItemActive: {
    backgroundColor: '#1e3a5f',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  dropdownMenuText: {
    color: '#222',
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  dropdownMenuTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  splashContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1e3a5f',
  },
  quoteOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    backgroundColor: 'rgba(30,58,95,0.35)',
  },
  quoteImageScrollContainer: {
    width: '100%',
    height: 220,
    overflow: 'hidden',
    position: 'relative',
  },
  quoteAuthor: {
    color: '#f7b731',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 1,
  },
  quoteBannerContainer: {
    width: '100%',
    backgroundColor: '#1e3a5f',
    marginBottom: 0,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  quoteBannerScroll: {
    width: '100%',
    height: 220,
    backgroundColor: '#1e3a5f',
  },
  quoteBannerContent: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  navText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '500',
    letterSpacing: 1,
    textAlign: 'center',
  },
  activeNavText: {
    color: '#1e3a5f',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'center',
  },
  contactSectionWhite: {
    backgroundColor: '#fff',
    paddingHorizontal: 0, // Remove horizontal padding so involvedBox can go edge-to-edge
    paddingVertical: 50,
    marginBottom: 0,
  },
  messageHeaderContainer: {
    alignItems: 'flex-start',
    marginBottom: 18,
    marginLeft: 4,
  },
  messageHeaderText: {
    color: '#1e3a5f',
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 6,
    letterSpacing: 1,
  },
  yellowBar: {
    width: 60,
    height: 7,
    backgroundColor: '#f7b731',
    borderRadius: 4,
    marginTop: 2,
    marginBottom: 8,
  },
  involvedBox: {
    backgroundColor: '#1e3a5f',
    paddingVertical: 24,
    paddingHorizontal: 0,
    marginLeft: 0,
    marginRight: 0,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    width: '100%',
    alignSelf: 'stretch',
  },
  involvedTitle: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    flex: 1,
    marginLeft: 18, // Move text to the right
  },
  eventButtonRight: {
    backgroundColor: '#f7b731',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 8,
    marginLeft: 10, // Move button a little more inward (left)
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  messageBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 24,
  },
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  topNavContainer: {
    backgroundColor: '#1e3a5f',
    borderBottomWidth: 2,
    borderBottomColor: '#1e3a5f',
    paddingVertical: 25,
    paddingTop: 70,
    paddingBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 1000,
  },
  navContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    height: 70,
  },
  logoContainer: {
    width: 100,
    height: 70,
    marginRight: 20,
    flexShrink: 0,
  },
  logoBackground: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 8,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  navLogo: {
    width: '100%',
    height: '100%',
  },
  navScrollView: {
    flex: 1,
  },
  navScrollContainer: {
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 25,
    minWidth: 100,
    height: 45,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  activeNavItem: {
    backgroundColor: '#f7b731',
    borderColor: '#f7b731',
  },
  quoteText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 6,
    lineHeight: 22,
    marginBottom: 6,
  },
  quoteBannerImage: {
    width: '100%',
    height: 440,
    opacity: 0.85,
  },
  splashLogo: {
    width: 300,
    height: 200,
  },
  mainContent: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  heroSection: {
    backgroundColor: '#1e3a5f',
    height: 400,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginBottom: 0,
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(30, 58, 95, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  heroContent: {
    alignItems: 'center',
    maxWidth: 600,
  },
  heroTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 42,
    fontFamily: 'System',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  heroSubtitle: {
    fontSize: 24,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: '600',
    fontFamily: 'System',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  heroYear: {
    fontSize: 18,
    color: '#f7b731',
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: 'System',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  mainContentContainer: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  missionSection: {
    marginBottom: 50,
  },
  missionTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1e3a5f',
    marginBottom: 20,
    textAlign: 'left',
    fontFamily: 'System',
  },
  missionText: {
    fontSize: 18,
    color: '#1e3a5f',
    lineHeight: 28,
    marginBottom: 25,
    fontWeight: '600',
    textAlign: 'left',
    fontFamily: 'System',
  },
  storySection: {
    marginBottom: 0,
  },
  sectionTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1e3a5f',
    marginBottom: 25,
    textAlign: 'left',
    fontFamily: 'System',
  },
  bodyText: {
    fontSize: 16,
    color: '#555555',
    lineHeight: 28,
    marginBottom: 20,
    textAlign: 'left',
    fontFamily: 'System',
  },
  linkButton: {
    alignSelf: 'flex-start',
    marginTop: 15,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#1e3a5f',
    borderRadius: 6,
  },
  linkText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '700',
  },
  placeholderContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  placeholderText: {
    fontSize: 18,
    color: '#666666',
  },
  contactSection: {
    backgroundColor: '#1e3a5f',
    paddingHorizontal: 20,
    paddingVertical: 50,
    marginBottom: 0,
  },
  contactHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
    flexWrap: 'wrap',
  },
  contactTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#ffffff',
    flex: 1,
  },
  eventButton: {
    backgroundColor: '#f7b731',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  eventButtonText: {
    color: '#1e3a5f',
    fontSize: 16,
    fontWeight: '700',
  },
  formTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 30,
    textAlign: 'left',
  },
  formContainer: {
    backgroundColor: 'transparent',
  },
  formRow: {
    flexDirection: 'row',
    marginBottom: 20,
    gap: 15,
  },
  formField: {
    flex: 1,
  },
  fullWidthField: {
    marginBottom: 20,
  },
  input: {
    backgroundColor: '#ffffff',
    height: 50,
    borderRadius: 6,
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#333',
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  messageInput: {
    backgroundColor: '#ffffff',
    height: 120,
    borderRadius: 6,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: '#333',
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sendButton: {
    backgroundColor: '#f7b731',
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  sendButtonText: {
    color: '#1e3a5f',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  }
});